import { DiagramGroup } from "../../scripts/canvas/diagramgroup";
import { createDiagramFrom } from "../../scripts/canvas/utils";
import { Lint } from "../../scripts/lint";
import { DialogType, Tutorial } from "../interface";
import { Poppy } from "../poppy";

export class Tutorial03 extends Tutorial {
    constructor() {
        super();
        this.name = "Loops";
        this.cursor = 0;
        Lint.autoOpen = false;
    }

    update() {
        switch(this.cursor) {
            case 0:
                Poppy.display({
                    message: "Welcome! In this lesson, we will learn about <span class=\"accent\">loops</span> in Python. Loops allow you to execute a block of code multiple times, which is useful for automating repetitive tasks.",
                    dialogType: DialogType.NEXT,
                    cb: (() => this.cursor = 1).bind(this)
                });
                break;
            case 1:
                Poppy.display({
                    message: "Let's start with the <span class=\"info\">for loop</span>. A for loop iterates over a sequence, such as a list, tuple, or range of numbers. This allows you to process each item in the sequence one at a time.",
                    dialogType: DialogType.NEXT,
                    cb: (() => this.cursor = 11).bind(this)
                });
                break;
            case 11:
                Poppy.display({
                    message: `First let's drag a <span class="accent">For loop</span> diagram to the editor`,
                    onDisplay: (() => {
                    const btn = document.querySelector("#btn-diagram-view")! as HTMLElement;
                        if ( !btn.classList.contains("active") ) {
                            btn.click();
                            const tname = btn.getAttribute("aria-target")!;
                            const target = document.querySelector("#" + tname)! as HTMLDivElement;
                            const diagram = document.querySelector("img[data-diagram-type=\"loop-for\"]")! as HTMLElement;
                            target.scrollTo({
                                top: 400,
                                behavior: "instant",
                            });
                            this.highlight(diagram, (() => {}), true);
                            const rect = diagram.getBoundingClientRect();
                            const targetPos = {
                                x: rect.x + rect.width + 5,
                                y: rect.y + 40
                            };
                            const distance = {
                                x: Math.abs(Poppy.pos.x - targetPos.x),
                                y: Math.abs(Poppy.pos.y - targetPos.y)
                            };
                            if (distance.x != 0 && distance.y != 0)
                            Poppy.targetPos = targetPos;
                        }
                    }).bind(this),
                    dialogType: DialogType.NONE,
                    timeout: -1
                });
                Poppy.onDiagramDrop = (() => {
                    let dgs = window.mCvRootNode.getDiagramGroups();
                    if (dgs.length == 0) {
                        return;
                    }
                    if (dgs[0].nodes[0].name() == "For") {
                        this.cursor = 2;
                        this.highlightRemove();
                        Poppy.qDialogRemoveFirst();
                        Poppy.update();
                        Poppy.onDiagramDrop = null;
                        return;
                    }
                }).bind(this);
                break;
            case 2:
                Poppy.display({
                    message: "Here’s how to use a for loop to print numbers from 0 to 4:<pre><span class=\"info\">for i in range(5):<br>   print(i)</span></pre> In this example, <span class=\"info\">i</span> takes on each value in the sequence generated by <span class=\"info\">range(5)</span>.",
                    dialogType: DialogType.NONE,
                    onDisplay: (() => {
                        const currentPos = Poppy.pos;
                        Poppy.targetPos = {
                            x: currentPos.x,
                            y: currentPos.y - 70
                        };
                    })
                });
                Poppy.addOnModified([
                    {
                        name: "main",
                        content: "for i in range(5):\n\tprint(i)\n"
                    }
                ], (() => this.cursor = 3).bind(this), (() => this.cursor = -1).bind(this));
                break;
            case 21:
                Poppy.display({
                    message: "Here’s how to use a for loop to print numbers from 0 to 4:<pre><span class=\"info\">for i in range(5):<br>   print(i)</span></pre> In this example, <span class=\"info\">i</span> takes on each value in the sequence generated by <span class=\"info\">range(5)</span>.",
                    dialogType: DialogType.NONE
                });
                Poppy.addOnModified([
                    {
                        name: "main",
                        content: "for i in range(5):\n\tprint(i)\n"
                    }
                ], (() => this.cursor = 3).bind(this), (() => this.cursor = -1).bind(this));
                break;
            case 3:
                Poppy.display({
                    message: "Try running this code to see the numbers printed. The <span class=\"info\">range(5)</span> function generates numbers starting from 0 up to, but not including, 5.",
                    dialogType: DialogType.NEXT,
                    cb: (() => this.cursor = 4).bind(this)
                });
                break;
            case 4:
                Poppy.display({
                    message: `Awesome! Now, let's explore the <span class=\"info\">while loop</span>. First let's <span class="accent">remove</span> the <span class="info">for loop diagram</span> we made. You can do so by <code>Right Click on the diagram</code> and click <span class="accent">Delete Module</span>`,
                    dialogType: DialogType.NONE,
                    timeout: -1
                });
                Poppy.onDelete = (() => {
                    let dgs = window.mCvRootNode.getDiagramGroups();
                    if (dgs.length == 0) {
                        this.cursor = 41;
                        Poppy.onDelete = null;
                        Poppy.qDialogRemoveFirst();
                        Poppy.update();
                        return;
                    }

                }).bind(this);
                break;
            case 41:
                Poppy.display({
                    message: `Now let's drag a <span class="accent">While loop</span> diagram to the editor`,
                    onDisplay: (() => {
                    const btn = document.querySelector("#btn-diagram-view")! as HTMLElement;
                        if ( !btn.classList.contains("active") ) {
                            btn.click();
                        }
                        const tname = btn.getAttribute("aria-target")!;
                        const target = document.querySelector("#" + tname)! as HTMLDivElement;
                        const diagram = document.querySelector("img[data-diagram-type=\"loop-while\"]")! as HTMLElement;
                        target.scrollTo({
                            top: 400,
                            behavior: "instant",
                        });
                        this.highlight(diagram, (() => {}), true);
                        const rect = diagram.getBoundingClientRect();
                        const targetPos = {
                            x: rect.x + rect.width + 5,
                            y: rect.y + 40
                        };
                        const distance = {
                            x: Math.abs(Poppy.pos.x - targetPos.x),
                            y: Math.abs(Poppy.pos.y - targetPos.y)
                        };
                        if (distance.x != 0 && distance.y != 0)
                        Poppy.targetPos = targetPos;
                    }).bind(this),
                    dialogType: DialogType.NONE,
                    timeout: -1
                });

                Poppy.onDiagramDrop = (() => {
                    let dgs = window.mCvRootNode.getDiagramGroups();
                    if (dgs.length == 0) {
                        return;
                    }
                    if (dgs[0].nodes[0].name() == "While") {
                        this.cursor = 42;
                        this.highlightRemove();
                        Poppy.qDialogRemoveFirst();
                        Poppy.update();
                        Poppy.onDiagramDrop = null;
                        return;
                    }
                }).bind(this);
                break;
            case 42:
                Poppy.display({
                    message: `A while loop continues executing as long as a given condition is true. This is useful when you don't know in advance how many times you'll need to iterate.`,
                    dialogType: DialogType.NEXT,
                    cb: (() => {
                        this.cursor = 5;
                        let dgs = window.mCvRootNode.getDiagramGroups()
                        let pos = dgs[0].position();
                        dgs.forEach((d) => {
                            d.remove();
                            d.destroy();
                        });
                        const dgGroup = new DiagramGroup(pos);
                        dgGroup.addDiagram(createDiagramFrom("statement"));
                        dgGroup.addDiagram(createDiagramFrom("while"));
                        dgGroup.refresh();
                        window.mCvRootNode.node.add(dgGroup);
                    }).bind(this)
                });
                break;
            case 5:
                Poppy.display({
                    message: "Here’s an example of a while loop that prints numbers from 0 to 4:<pre><span class=\"info\">i = 0<br>while i < 5:<br>    print(i)<br>    i += 1</span></pre> In this code, we start with <span class=\"info\">i</span> equal to 0 and continue looping as long as <span class=\"info\">i</span> is less than 5.",
                    dialogType: DialogType.NONE
                });
                Poppy.addOnModified([
                    {
                        name: "main",
                        content: "i = 0\nwhile i < 5:\n\tprint(i)\n\ti += 1\n"
                    }
                ], (() => this.cursor = 6).bind(this), (() => {} ).bind(this));
                // remove onFail editing gets interupted
                break;
            case 6:
                Poppy.display({
                    message: "Try running this code to see how the while loop works. It keeps printing as long as <span class=\"info\">i</span> is less than 5. Notice that we increment <span class=\"info\">i</span> by 1 with each iteration.",
                    dialogType: DialogType.NEXT,
                    cb: (() => this.cursor = 7).bind(this)
                });
                break;
            case 7:
                Poppy.display({
                    message: "Great job! Loops are powerful tools for automating repetitive tasks. You can try changing the range or the condition in the while loop to see how it affects the output!",
                    dialogType: DialogType.NEXT,
                    cb: (() => this.cursor = 8).bind(this)
                });
                break;
            case -1:
                Poppy.display({
                    message: "Hmm, it seems something went wrong. Did you type the for loop correctly? Make sure it's exactly like the example.",
                    dialogType: DialogType.NEXT,
                    cb: (() => this.cursor = 21).bind(this)
                });
                break;
            case -2:
                Poppy.display({
                    message: "Hmm, it seems something went wrong. Did you type the while loop correctly? Double-check your syntax and try again.",
                    dialogType: DialogType.NEXT,
                    cb: (() => this.cursor = 5).bind(this)
                });
                break;
            default:
                Poppy.tutorial = null;
                console.log("End of tutorial");
                break;
        }
    }

    highlightRemove() {
        const highlighters = document.querySelectorAll(".highlighter")
        highlighters.forEach((v) => v.remove());
    }

    highlight(el: HTMLElement, cb?: () => void, ignoreEvents = false) {
        this.highlightRemove();
        const div = document.createElement("div");
        const rect = el.getBoundingClientRect();
        div.classList.add("highlighter");
        div.style.left = `${rect.x}px`;
        div.style.top = `${rect.y}px`;
        div.style.width = `${rect.width}px`;
        div.style.height = `${rect.height}px`;
        if (ignoreEvents) {
            div.style.pointerEvents = "none";
        }
        let ref = this;
        div.addEventListener("click", (e) => {
            e.preventDefault();
            if (el instanceof HTMLButtonElement)
                el.click();
            ref.highlightRemove();
            if (cb)
                cb();
            Poppy.update();
        });
        document.body.appendChild(div);
    }
}
