name: Build App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    env:
      RUSTUP_TOOLCHAIN: 1.76  # Set the default Rust version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      # Install Rust and set the version to 1.76
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76
          override: true

      # Install Windows dependencies
      - name: Install MSVC C++ Build Tools and SDK
        run: |
          choco install visualstudio2019buildtools --params "'/InstallPath C:\\BuildTools'"
          choco install windows-sdk-10.0

      # Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Install Tauri CLI
      - name: Install Tauri CLI
        run: cargo install tauri-cli --version 1.5.10 --locked

      # Build the Tauri app
      - name: Build Tauri App
        run: cargo tauri build
      # Compress the bundle folder to a ZIP file
      - name: Compress Build Output
        run: |
          powershell Compress-Archive -Path src-tauri/target/release/bundle -DestinationPath Teacher-Poppy.zip

      # Upload the ZIP file as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Teacher Poppy ZIP
          path: Teacher-Poppy.zip
